# when using the default proxy server port
local_backend: true
backend:
  name: git-gateway

publish_mode: editorial_workflow
site_url: https://prjedem.org
media_folder: src/public/media
public_folder: /media
locale: ru
media_library:
  max_file_size: 512000
  folder_support: true
slug:
  encoding: ascii
  clean_accents: true
i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en
  enforce_required_non_default: false
collections:
  - name: docs
    label: Docs
    i18n: true
    folder: "src"
    path: "post/{{slug}}"
    slug: "{{year}}-{{slug}}"
    create: true
    # filter:
    #   pattern: "^ec"
    # filter:
    #   field: dirname
    #   value: "post"
    summary: "{{dirname}} {{pubDate | date('yyyy-MM-dd')}} {{filename}} {{title}}"
    sortable_fields:
      fields: ["pubDate", "title", "authorId"]
      default:
        field: pubDate
        direction: Descending
    view_groups:
      default: by-year
      groups:
        - name: by-year
          label: Year
          field: pubDate
          pattern: \d{4}
        - name: by-author
          label: Author
          field: authorId
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: Publication date and hour UTC
        name: pubDate
        widget: datetime
        format: yyyy-MM-dd'T'HH
        i18n: duplicate
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        i18n: true
      - label: "Replace text for preview for articles and list items"
        name: "previewText"
        widget: "text"
        required: false
        i18n: true
      - label: "Use description as a preview (if not set previewText)"
        name: "descrAsPreview"
        widget: "boolean"
        default: true
        i18n: duplicate
      - label: "commentUrl"
        name: "commentUrl"
        widget: "string"
        required: false
        i18n: true
      - label: "videoLink"
        name: "videoLink"
        widget: "string"
        required: false
        i18n: true
      - name: tags
        label: Tags (separated by coma)
        widget: list
        required: false
        i18n: true
        # {
        #   "name": "tags",
        #   "label": "Tags",
        #   "widget": "relation",
        #   "i18n": true,
        #   "collection": "tags",
        #   "multiple": true,
        #   "value_field": "id",
        #   "search_fields": [
        #     "id"
        #   ],
        #   "display_fields": [
        #     "languages.cs",
        #     "languages.en"
        #   ]
        # },
      # {
      #      "name": "tags",
      #      "label": "Tags",
      #      "label_singular": "Tag",
      #      "folder": "src/content/tags",
      #      "identifier_field": "id",
      #      "create": true,
      #      "delete": true,
      #      "i18n": false,
      #      "slug": "{{id}}",
      #      "extension": "json",
      #      "fields": [
      #        {
      #          "name": "id",
      #          "label": "Tag dentifier",
      #          "widget": "string",
      #          "i18n": "duplicate"
      #        },
      #        {
      #          "name": "languages",
      #          "label": "Translations",
      #          "widget": "object",
      #          "fields": [
      #            {
      #              "name": "cs",
      #              "label": "Čeština - tag translation",
      #              "widget": "string",
      #              "i18n": false
      #            },
      #            {
      #              "name": "en",
      #              "label": "English - tag translation",
      #              "widget": "string",
      #              "i18n": false
      #            }
      #          ]
      #        }
      #      ]
      #    }     #
      - name: authorId
        label: Author
        widget: select
        options: ["ivan-k"]
        required: false
        i18n: duplicate
      - label: "Body"
        name: "body"
        widget: "markdown"
        i18n: true
        show_raw: true
